Python
nkdash001/hello2021 pull request #1
Opened 2021-05-06 17:25 UTC by snehanshup

name changed pull request

2021-05-06 17:26 UTC, snehanshup commented
looks good to me

2021-05-06 17:27 UTC, nkdash001 requested changes
change name to my name

2021-05-06 17:27 UTC, nkdash001 commented on intro.py
> +print "(My name is snehanshu)"
you need to change this to my name

2021-05-06 17:33 UTC, snehanshup reviewed
nice

2021-05-06 17:39 UTC, nkdash001 approved these changes

2021-05-06 17:39 UTC, nkdash001 approved these changes

2021-05-06 17:44 UTC, snehanshup commented
ok done

2021-05-06 17:46 UTC, snehanshup commented on intro.py
> +print "(My name is snehanshu)"
done

2021-05-06 17:48 UTC, snehanshup reviewed
alright fine  LGTM

2021-05-08 17:24 UTC, snehanshup commented
closed

2021-05-08 17:24 UTC, closed without merging